name: Build Debian Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y lintian devscripts debhelper

    - name: Build DEB Package
      run: |
        debuild -us -uc
        mv ../*.deb .

    - name: Lintian
      run: lintian *.deb

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: "*.deb"

